### ISSUE TITLE
list_rules :role filter not working

### ISSUE THREAD

**Issue by benonymus** [woylie/let_me#24]
Hey,

**Describe the bug**

It seems like role scoped introspection of rules is not working.
In the docs: https://hexdocs.pm/let_me/readme.html#introspection 
it is stated that it is possible to return a list of rules by role: ` MyApp.Policy.list_rules(role: :writer)`

This does not seem to work. 
I get the following error when I try:

```
XXX.Policy.list_rules(role: :admin)
** (ArgumentError) unknown keys [:role] in [role: :admin], the allowed keys are: [:action, :allow, :deny, :object]
    (elixir 1.14.2) lib/keyword.ex:355: Keyword.validate!/2
    (let_me 1.0.1) lib/let_me.ex:68: LetMe.filter_rules/2
    iex:2: (file)

```

**To Reproduce**
We have a Policy file set up based on the docs, other list_rules/1 filters seem to work.

**Expected behavior**
Expecting to get a list of rules back that are relevant to the role.

**Versions:**
 - LetMe: 1.0.1
 - Elixir: 1.14.2
 - Erlang: 25

**Comment by woylie** [comment]
Thanks for the report. That seems to be a typo in the example. Can you try running `XXX.Policy.list_rules(allow: {:role, :admin})`?

**Comment by benonymus** [comment]
Ah that works! 
Thanks!
