### ISSUE TITLE
Policy.filter_allowed_actions/3 does not accept a schema module instead of a tuple

### ISSUE THREAD

**Issue by sesamzoo** [woylie/let_me#58]
**Describe the bug**
The following part of the documentation
> If you registered the schema module with `LetMe.Policy.object/3`, you can also
> ***pass the schema module*** or the struct instead of a tuple.

lets me think that I could this:
```elixir
MyPolicy.filter_allowed_actions(my_rules, :my_object, MyObjectSchemaModule)
```
but due to the callback's guards it leads to this error:
```shell
    Attempted function clauses (showing 2 out of 2):
    
        def filter_allowed_actions(rules, subject, {object_name, object}, policy) when is_list(rules) and is_atom(object_name)
        def filter_allowed_actions(rules, subject, %_{} = object, policy)
```

Is my interpretation of the documentation incorrect or is the implementation (accidentally) lacking support to just "pass the schema module"?

**To Reproduce**

See above.

**Expected behavior**
I'd expect 
```elixir
MyPolicy.filter_allowed_actions(my_rules, :my_object, MyObjectSchemaModule)
```
to return the list of matching rules.

**Versions:**

- LetMe: 1.2.2
- Elixir: 1.15.6
- Erlang: 26.1

**Additional context**
I [commented](https://github.com/woylie/let_me/commit/dbe79027f28fee2c2aa47ee850a0e6ba80955f0b#r130986316) the commit that introduced the statement in the documentation.

**Comment by woylie** [comment]
Thanks for opening the issue! That was a mistake in the documentation. While `get_object_name/1` allows passing the schema module, the filter functions needs the actual struct, since it applies all policy rules on the given subject and object. I updated the documentation in #60.
